import os, time, random
import osha.loadtest.base
from funkload.utils import xmlrpc_get_seq
import funkload.Lipsum
LIPSUM = funkload.Lipsum.Lipsum()    

class heavy(osha.loadtest.base.TestCase):
    group = 'heavyusagegroup'
    chost,cport = os.environ.get('LOADTEST_CREDENTIAL_SERVER').split(':')
    workspaces = []
    

                  
    def test_heavy(self):
        """
        * Login via the main home page URL
        * Logoff
        """

        self.login()
        self.assertEllipsis('...You are now logged in...', self.getBody())
        self.get('/en/tmp/')
        self.assertEllipsis('...Contents...View...Edit...', self.getBody())
        self.create_document('myfunkloaddoc')
        self.get('/en/practical-solutions')
        self.assertEllipsis('...Practical Solutions...Online interactive Risk Assessment tool...', self.getBody())
        self.get('/en/practical-solutions/useful-links')
        self.assertEllipsis('...Search in the USEFUL LINKS DATABASE...', self.getBody())
        self.get('/en/practical-solutions/case-studies')
        self.assertEllipsis('...Case Studies...', self.getBody())
        # error
        # self.get('/en/practical-solutions/case-studies/index_html/practical-solution?SearchableText=studies&is_search_expanded=&getRemoteLanguage=en&keywords%3Alist=&nace2=&multilingual_thesaurus2=&submit=Search')
        # self.assertEllipsis('...Case Studies...CASE STUDIES DATABASE... HEALTHY... NANOPOWDERS...AGRIPROTECT...', self.getBody())
        self.get('/en/press')
        self.assertEllipsis('...Press Room...Contents...View...Edit...', self.getBody())
        self.get('/en/press/press-releases')
        self.assertEllipsis('...Press Releases...', self.getBody())
        self.get('/en/press/photos/animation/animations')
        self.assertEllipsis('...Contents...View...Edit...', self.getBody())
        # upload .gif, .jpg wie?
        # self.get('/en/press/photos/animation/animations')
        # self.assertEllipsis('...Contents...View...Edit...', self.getBody())
        self.get('/en/press/photos/competitions/photo-competition-2011/maksymowicz/@@multimedia-image-details-view')
        self.assertEllipsis('...Dressmaker by Krzysztof Maksymowicz (1st Prize)...', self.getBody())
        # self.get('/en/napos-films')
        # self.assertEllipsis('...', self.getBody())
        self.get('/nl')
        self.assertEllipsis('...Highlights...In Focus...Menu...Gratis nieuwsbrief...Latest Tweets...', self.getBody())
        # self.get('/es/napos-films')
        # self.assertEllipsis('...', self.getBody())
        self.get('/en/about/jobs')
        self.assertEllipsis('...Job vacancies...More about...Free Newsletter...', self.getBody())
        # self.get('/pt/napos-films')
        # self.assertEllipsis('...', self.getBody())
        # self.get('/en/napo-for-teachers')
        # self.assertEllipsis('...', self.getBody())
        self.get('/lv')
        self.assertEllipsis('...Highlights...In Focus...Bezmaksas...Latest Tweets...', self.getBody())
        # defekte Seite
        self.get('/fop/spain/es')
        self.assertEllipsis('...Sistema de Seguridad y Salud en el Trabajo de ...Busca algo...Noticias nacionales...Noticias legislativas nacionales...', self.getBody())
        self.get('/de')
        self.assertEllipsis('...Highlights...In Focus...Kostenloser Newsletter...Latest Tweets...', self.getBody())
        # self.get('/fr/napos-films')
        # self.assertEllipsis('...', self.getBody())
        self.get('/en/publications')
        self.assertEllipsis('...Publications...', self.getBody())
        self.get('/en/organisations')
        self.assertEllipsis('...Organisations and strategies...OSH Strategies...More about...Publications...', self.getBody())
        self.get('/en/publications/literature_reviews')
        self.assertEllipsis('...Literature reviews...Free Newsletter...Press Releases...', self.getBody())
        # self.get('/en/napos-films/napoepisode?filmid=napo-017-working-together')
        # self.assertEllipsis('...', self.getBody())
        # self.get('/es/napos-films/napoepisode?filmid=napo-017-working-together')
        # self.assertEllipsis('...', self.getBody())
        # self.get('/Events/oshmail/sub/en')
        # self.assertEllipsis('...', self.getBody())
        self.get('/en/topics/riskassessment/')
        self.assertEllipsis('...Risk assessment...OiRA - Online interactive Risk Assessment project...Online interactive Risk Assessment tool...More about...', self.getBody())
        self.get('/en/topics/riskassessment/guidance.pdf')
        self.get('/en/news/oshmail')
        self.assertEllipsis('...OSHmail newsletter...', self.getBody())
        self.get('/en/events/ ')
        self.assertEllipsis('...OSHEvents...', self.getBody())
        self.get('/fi/oshnetwork/focal-points/finland')
        self.assertEllipsis('...Suomi...', self.getBody())
        self.get('/en/press/photos/napo')
        self.assertEllipsis('...Napo...', self.getBody())
        # self.get('/Events/oshmail/sub/en')
        # self.assertEllipsis('...', self.getBody())
        self.get('/en/topics')
        self.assertEllipsis('...Contents...View...Edit...', self.getBody())
        self.get('/en/practical-solutions')
        self.assertEllipsis('...Practical Solutions...', self.getBody())
        # self.get('/pt/napos-films')
        # self.assertEllipsis('...', self.getBody())
        # self.get('/it/napos-films')
        # self.assertEllipsis('...', self.getBody())
        # self.get('/nl/napos-films')
        # self.assertEllipsis('...', self.getBody())
        self.get('/en/oshnetwork/focal-points')
        self.assertEllipsis('...National Focal Points...National Focal Points... ', self.getBody())
        self.get('/en/legislation/guidelines')
        self.assertEllipsis('...European Guidelines...', self.getBody())
        self.get('/en/seminars')
        self.assertEllipsis('...Latest Seminars...', self.getBody())
        # the search shows no results (?)
        # self.get('/en/seminars/index_html/@@seminar-search?st=spl&SearchableText=Healthy')
        # self.assertEllipsis('...', self.getBody())
        self.get('/en/practical-solutions/risk-assessment-tools')
        self.assertEllipsis('...RISK ASSESSMENT TOOLS DATABASE...', self.getBody())
        # self.get('http://oshawebdev00.fe.rzob.gocept.net/en/practical-solutions/risk-assessment-tools/index_html/practical-solution?SearchableText=Workplace&is_search_expanded=&getRemoteLanguage=en&keywords%3Alist=&nace2=&multilingual_thesaurus2=&submit=Search')
        # self.assertEllipsis('... Building...Guide...Reducing...', self.getBody())
        self.create_file('testfilefunkload')
        self.logout()


